set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
set client_min_messages = WARNING;
alter table if exists CreditCard drop constraint if exists FKnwxb2pvuwnkoifgrp2d14pla0;
alter table if exists CreditCard drop constraint if exists FKfky0y471d7n8cebc1oe28idci;
alter table if exists Customer_Address drop constraint if exists FK5ov3y8x18tb2tfs01klxn7g7o;
alter table if exists Customer_Address drop constraint if exists FKpunprton0xne8mjk0r6carq6n;
alter table if exists customer_creditcard drop constraint if exists FKbqtt4y8vkl6a0hk4ud19wci0g;
alter table if exists customer_creditcard drop constraint if exists FKfjq2xyx1jh83r4h1t7f18kxj;
drop table if exists Address cascade;
drop table if exists Bank cascade;
drop table if exists CreditCard cascade;
drop table if exists Customer cascade;
drop table if exists Customer_Address cascade;
drop table if exists customer_creditcard cascade;
drop table if exists Pincode cascade;
